require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'doctell' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'




  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


  target 'doctellTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'doctell-tvOS' do
  # Pods for doctell-tvOS

  target 'doctell-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
